name = "sueiyue-news"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "sueiyue-news-db"
database_id = "0187c662-f529-4d52-ae29-ea384ced649b"
